@startuml bdd
!define table(x) class x << (T,#FFAAAA) >>
hide methods
hide stereotypes
table(Historique) {
    {static} id : UUID
}
table(Message) {
    {static} id: integer
    contenu : text
    date : timestamp
    fichier : boolean
    recu : boolean
}
Historique "1" -- "*" Message
@enduml
