@startuml
sprite $clavardage [16x16/16] {
FFFFFFFFFFFFFFFF
FFF000000000FFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFF0FFFFF
FFFFFFFFFF00FFFF
FF00000000000FFF
FF000000000000FF
FF00000000000FFF
FFFFFFFFFF00FFFF
FFFFFFFFFF0FFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}

rectangle "Application de clavardage" <<$clavardage>> {
  
    component ControleurUtilisateurs
    component ControleurSession
    component ControleurUDP
    component ControleurTCP

    component AccessDB
    component AccessTCP
    component AccessUDP

    component ModeleSession
    component ModeleUtilisateurs

    component ServiceReceptionUDP
    component ServiceReceptionConnexionTCP
    component ServiceReceptionTCP

    ControleurUtilisateurs --> AccessTCP
    ControleurUtilisateurs --> AccessUDP
    ControleurUtilisateurs <--> ModeleUtilisateurs

    ModeleSession <--> AccessDB

    ControleurSession <--> ModeleSession
    ControleurSession <--> ServiceReceptionTCP

    AccessTCP <--> ServiceReceptionConnexionTCP
    AccessUDP <--> ServiceReceptionUDP

    ControleurUDP <-- ServiceReceptionUDP
    ControleurTCP <-- ServiceReceptionTCP


}
cloud "Réseau local" as net
database "Base de données" as bdd
actor "Employé"as emp

AccessDB --> bdd

ServiceReceptionTCP <-- net
ServiceReceptionUDP <-- net
ServiceReceptionConnexionTCP <--> net

ControleurUtilisateurs <-u- emp
ControleurUDP <-u- emp
ControleurSession <-u-> emp
ControleurTCP <-u-> emp
@enduml