@startuml Connexion
actor Employe
group seq [connexion locale]
    Employe -> Principal : main()
    activate Principal
    Principal -> VueApplication : start()
    activate VueApplication 
    VueApplication -> ControleurUtilisateurs : ControleurUtilisateurs()
    activate ControleurUtilisateurs
    ControleurUtilisateurs -> ControleurUDP : ControleurUDP(udp)
    activate ControleurUDP
    ControleurUDP -> ServiceReceptionUDP : start()
    activate ServiceReceptionUDP
    ControleurUDP --> ControleurUtilisateurs : udp
    deactivate ControleurUDP
    ControleurUtilisateurs -> ControleurTCP : ControleurTCP(tcp)
    activate ControleurTCP
    ControleurTCP -> ServiceReceptionTCP : start()
    activate ServiceReceptionTCP
    ControleurTCP --> ControleurUtilisateurs : tcp
    deactivate ControleurTCP
    ControleurUtilisateurs -> ModeleUtilisateurs : ModeleUtilisateurs()
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUtilisateurs : modele
    deactivate ModeleUtilisateurs
    ControleurUtilisateurs -> VueUtilisateurs : VueUtilisateurs(controleur, modele)
    activate VueUtilisateurs
    ref over ControleurUtilisateurs
        Saisie de 
        pseudo
    end ref
    deactivate ControleurUtilisateurs
end
group seq [connexion distante]
    ServiceReceptionUDP -> ControleurUDP : receptionUtilisateur(identifiant, adresse, pseudo)
    activate ControleurUDP
    ref over ControleurUDP
        Validation de
            pseudo
    end ref
    ControleurUDP -> ModeleUtilisateurs : connexion(utilisateur)
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUDP
    deactivate ModeleUtilisateurs
    deactivate ControleurUDP
end
@enduml
