@startuml creation_session
activate ControleurUtilisateurs
ControleurUtilisateurs -> ControleurSession : ControleurSession(socket, utilisateur)
activate ControleurSession
ControleurSession -> ControleurBDD : instance()
activate ControleurBDD
ControleurBDD --> ControleurSession : bdd
deactivate
ref over ControleurSession
    Récupération de
        l'historique
end ref
ControleurSession -> ServiceCommunicationTCP : start(socket)
activate ServiceCommunicationTCP
ControleurSession -> ModeleSession : ModeleSession(utilisateur, historique)
activate ModeleSession
ModeleSession --> ControleurSession : modele
deactivate ModeleSession
ControleurSession -> VueSession : VueSession(controleur, modele)
deactivate ControleurSession
activate VueSession
@enduml