@startuml Deconnexion
actor Employe
VueApplication [hidden]-> ControleurUtilisateurs
VueApplication [hidden]-> ControleurUDP
VueApplication [hidden]-> ServiceEnvoiUDP
group seq [deconnexion locale]
    VueApplication [hidden]-> ServiceReceptionUDP
    activate VueApplication
    activate ServiceReceptionUDP
    Employe -> VueApplication : deconnexion()
    VueApplication -> ControleurUtilisateurs : deconnexion()
    activate ControleurUtilisateurs
    ControleurUtilisateurs -> ControleurUDP : deconnexion()
    activate ControleurUDP
    ControleurUDP -> ServiceEnvoiUDP : start(paquet)
    activate ServiceEnvoiUDP
    ServiceEnvoiUDP --> ControleurUDP
    deactivate ServiceEnvoiUDP
    ControleurUDP --> ControleurUtilisateurs
    deactivate ControleurUDP
    ControleurUtilisateurs --> VueApplication
    deactivate ControleurUtilisateurs
    VueApplication -> VueApplication : fermeture()
    VueApplication [hidden]-> VueApplication
    deactivate ServiceReceptionUDP
    deactivate VueApplication
end
group seq [deconnexion distante]
    VueApplication [hidden]-> ControleurUtilisateurs
    activate VueApplication
    activate ServiceReceptionUDP
    ServiceReceptionUDP -> ControleurUDP : deconnexionDistante(identifiant)
    activate ControleurUDP
    ControleurUDP -> ControleurUtilisateurs : deconnexionDistante(identifiant)
    activate ControleurUtilisateurs
    ControleurUtilisateurs -> ModeleUtilisateurs : deconnexion(identifiant)
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUtilisateurs
    deactivate ModeleUtilisateurs
    ControleurUtilisateurs --> ControleurUDP
    deactivate ControleurUtilisateurs
    deactivate ControleurUDP
end
@enduml