@startuml deconnexion
actor Employe
ControleurUtilisateurs [hidden]-> AccesUDP
ControleurUtilisateurs [hidden]-> TacheEnvoiUDP
group seq [deconnexion locale]
    ControleurUtilisateurs [hidden]-> ServiceReceptionUDP
    activate ControleurUtilisateurs
    activate ServiceReceptionUDP
    Employe -> ControleurUtilisateurs : deconnexion()
    ControleurUtilisateurs -> AccesUDP : broadcastDeconnexion(utilisateur)
    note left of ControleurUtilisateurs
    utilisateur : Utilisateur
    msg : String
    adr : InetAdress
    broadcast : boolean
    end note
    activate AccesUDP
    AccesUDP -> TacheEnvoiUDP : TacheEnvoiUDP(msg, adr, broadcast)
    activate TacheEnvoiUDP
    AccesUDP --> ControleurUtilisateurs
    deactivate AccesUDP
    ControleurUtilisateurs -> ControleurUtilisateurs : fermeture()
    deactivate ServiceReceptionUDP
    deactivate TacheEnvoiUDP
    deactivate ControleurUtilisateurs
end
group seq [deconnexion distante]
    ServiceReceptionUDP -> AccesUDP : deconnexionDistante(identifiant)
    activate ServiceReceptionUDP
    activate AccesUDP
    AccesUDP -> ControleurUtilisateurs : deconnexionDistante(identifiant)
    activate ControleurUtilisateurs
    ControleurUtilisateurs -> ModeleUtilisateurs : setEtat(identifiant, etat)
    note left of ControleurUtilisateurs
    identifiant : UUID
    etat : EtatUtilisateur
    end note
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUtilisateurs
    deactivate ModeleUtilisateurs
    ControleurUtilisateurs --> AccesUDP
    deactivate ControleurUtilisateurs
    deactivate AccesUDP
end
@enduml
