@startuml enregistrement_historique
activate ModeleSession
note right of AccesDB
msg : MessageAffiche
end note
    ref over ModeleSession
        Envoi d'un
         message
    end ref
    ref over ModeleSession
        Réception d'un
            message
    end ref
ModeleSession -> AccesDB : ajoutMessage(msg)
activate AccesDB
database SQLite
AccesDB -> SQLite : INSERT INTO ...
activate SQLite
SQLite --> AccesDB
deactivate SQLite
AccesDB --> ModeleSession
deactivate AccesDB
@enduml
