@startuml envoi_message
actor Employe
activate ControleurSession
activate ServiceCommunicationTCP
group seq [envoi d'un messsage textuel]
    Employe -> ControleurSession : ecrireTexte(texte)
end
group seq [envoi d'un fichier]
    Employe -> ControleurSession : selectionFichier(fichier)
end
activate ControleurSession
ControleurSession -> ModeleSession : ajoutEnvoi(msg)
activate ModeleSession
ModeleSession --> ControleurSession
deactivate ModeleSession
ControleurSession -> TacheEnvoiTCP : TacheEnvoiTCP(sock, msg)
note left of TacheEnvoiTCP
texte : String
fichier : File
msg : MessageAffiche
sock : Socket
end note
activate TacheEnvoiTCP
deactivate TacheEnvoiTCP
alt ok
    ServiceCommunicationTCP -> ControleurSession : messageok()
    ControleurSession -> ModeleSession : envoiTermine()
    ref over ModeleSession
        Enregistrement dans
            l'historique
    end ref
    activate ModeleSession
    ModeleSession --> ControleurSession : msg
    deactivate ModeleSession
else erreur
    ServiceCommunicationTCP -> ControleurSession : erreurEnvoi()
    ControleurSession -> ModeleSession : erreurEnvoi()
    activate ModeleSession
    ModeleSession --> ControleurSession : msg
    deactivate ModeleSession
end
deactivate ControleurSession
@enduml
