@startuml envoi_message
actor Employe
activate VueSession
activate ServiceCommunicationTCP
group seq [envoi d'un messsage textuel]
    Employe -> VueSession : ecrireTexte(texte)
end
group seq [envoi d'un fichier]
    Employe -> VueSession : selectionFichier(fichier)
end
VueSession -> ControleurSession : envoiMessage(msg)
activate ControleurSession
ControleurSession -> ServiceCommunicationTCP : envoi(paquet)
ServiceCommunicationTCP --> ControleurSession : reception
alt reception = true
    ControleurSession [hidden]-> ControleurSession
    ref over ControleurSession
        Enregistrement dans
            l'historique 
    end ref
    ControleurSession -> ModeleSession : ajoutMessage(msg)
    activate ModeleSession
    ModeleSession --> ControleurSession
    deactivate ModeleSession
else reception = false
    ControleurSession -> ModeleSession : ajoutErreurMessage(msg)
    activate ModeleSession
    ModeleSession --> ControleurSession
    deactivate ModeleSession
end
ControleurSession --> VueSession
deactivate ControleurSession
@enduml