@startuml fermeture_session
actor Employe
activate ControleurSession
activate ServiceCommunicationTCP
group seq [fermeture locale]
    Employe -> ControleurSession : fermetureLocale()
    ControleurSession ->  TacheEnvoiTCP : TacheEnvoiTCP(sock, msg)
    activate TacheEnvoiTCP
    note left of ControleurSession
    sock : Socket
    msg : Fin
    end note
    ControleurSession -> ModeleSession : fermetureDB
    deactivate TacheEnvoiTCP
    activate ModeleSession
    ModeleSession -> AccesDB : close()
    activate AccesDB
    AccesDB --> ModeleSession
    deactivate AccesDB
    ModeleSession --> ControleurSession
    deactivate ModeleSession
    ControleurSession -> ServiceCommunicationTCP : cancel()
    deactivate ServiceCommunicationTCP
    deactivate ControleurSession
end
ControleurSession -[hidden]-> ServiceCommunicationTCP
activate ServiceCommunicationTCP
activate ControleurSession
group seq [fermeture distante]
    ServiceCommunicationTCP -> ControleurSession : fermetureDistante()
    ControleurSession -> ControleurSession : notificationFermeture()
    Employe -> ControleurSession : ok
    ControleurSession -> ModeleSession : fermetureDistante()
    activate ModeleSession
    ModeleSession -> AccesDB : close()
    activate AccesDB
    AccesDB --> ModeleSession
    deactivate AccesDB
    ModeleSession --> ControleurSession
    deactivate ModeleSession
    ControleurSession -> ServiceCommunicationTCP : cancel()
    deactivate ServiceCommunicationTCP
end
@enduml
