@startuml reception_message
activate ControleurSession
note left of ControleurSession
msg : MessageAffiche
sock : Socket
end note
activate ServiceCommunicationTCP
ServiceCommunicationTCP -> ControleurSession : receptionMessage(msg)
ControleurSession -> ModeleSession : enregistrerReception(msg)
activate ModeleSession
ref over ModeleSession
    Enregistrement dans
          l'historique
end ref
ModeleSession --> ControleurSession
deactivate ModeleSession
ServiceCommunicationTCP -> MessageOK : MessageOK(sock)
activate MessageOK
@enduml
