@startuml recuperation_historique
activate ControleurSession
ControleurSession -> ModeleSession : getDerniersMessages()
activate ModeleSession
ModeleSession -> AccesDB : getDerniersMessages()
activate AccesDB
database SQLite
note over SQLite
result : ResultSet
historique : List<MessageAffiche>
end note
AccesDB -> SQLite : SELECT * FROM ....
activate SQLite
SQLite --> AccesDB : result
deactivate SQLite
AccesDB --> ModeleSession : historique
deactivate AccesDB
ModeleSession --> ControleurSession : historique
deactivate ModeleSession
@enduml
