@startuml saisie_pseudo
actor Employe
activate ControleurUtilisateurs
ControleurUtilisateurs -> VueSaisiePseudo : saisiePseudo()
activate VueSaisiePseudo
Employe -> VueSaisiePseudo : pseudo
VueSaisiePseudo --> ControleurUtilisateurs
deactivate VueSaisiePseudo
ControleurUtilisateurs -> ModeleUtilisateurs : setPseudoLocal(pseudo)
activate ModeleUtilisateurs
ModeleUtilisateurs --> ControleurUtilisateurs
deactivate ModeleUtilisateurs
note over ModeleUtilisateurs
pseudo : String
end note
ref over ControleurUtilisateurs
    Validation d'un
        pseudo
end ref
@enduml
