@startuml saisie_pseudo
actor Employe
activate ControleurUtilisateurs
ControleurUtilisateurs -> ControleurSaisiePseudo : saisiePseudo()
activate ControleurSaisiePseudo
Employe -> ControleurSaisiePseudo : pseudo
ControleurSaisiePseudo --> ControleurUtilisateurs
deactivate ControleurSaisiePseudo
ControleurUtilisateurs -> ModeleUtilisateurs : setPseudoLocal(pseudo)
activate ModeleUtilisateurs
ModeleUtilisateurs --> ControleurUtilisateurs
deactivate ModeleUtilisateurs
note over ModeleUtilisateurs
pseudo : String
end note
ref over ControleurUtilisateurs
    Validation d'un
        pseudo
end ref
@enduml
