@startuml validation_pseudo
actor Employe
activate ServiceReceptionUDP
activate ControleurUtilisateurs
group seq [envoi pour validation]
    ControleurUtilisateurs -> ModeleUtilisateurs : getIdentifiantLocal()
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUtilisateurs : local
    deactivate ModeleUtilisateurs
    ControleurUtilisateurs -> AccesUDP : broadcastValidation(idLocal, pseudo)
    activate AccesUDP
    AccesUDP -> TacheEnvoiUDP : TacheEnvoiUDP(msg, adr, broadcast)
    activate TacheEnvoiUDP
    note over ServiceReceptionUDP
    local : Utilisateur
    idLocal : UUID
    identifiant : UUID
    msg : String
    pseudo : String
    adr : InetAddress
    broadcast : boolean
    udp : AccesUDP
    end note
    deactivate TacheEnvoiUDP
    AccesUDP --> ControleurUtilisateurs
    deactivate AccesUDP
end
group seq [reception pseudo choisi invalide]
    ServiceReceptionUDP -> TacheParseUDP : TacheParseUDP(udp, msg, adr)
    activate TacheParseUDP
    TacheParseUDP -> AccesUDP : pseudoLocalInvalide()
    deactivate TacheParseUDP
    activate AccesUDP
    AccesUDP -> ControleurUtilisateurs : saisiePseudo()
    deactivate AccesUDP
    ref over ControleurUtilisateurs
        Saisie de
          pseudo
    end ref
end
ServiceReceptionUDP -[hidden]-> ControleurUtilisateurs
group seq [changement ou connexion distante]
    activate AccesUDP
    AccesUDP -> ControleurUtilisateurs : validationDistante(identifiant, pseudo)
    deactivate AccesUDP
    ControleurUtilisateurs -> ModeleUtilisateurs : getPseudoLocal()
    activate ModeleUtilisateurs
    ModeleUtilisateurs --> ControleurUtilisateurs : pseudoLocal
    deactivate ModeleUtilisateurs
    alt pseudo != pseudoLocal
        ControleurUtilisateurs -> ModeleUtilisateurs : setPseudo(identifiant, pseudo)
        activate ModeleUtilisateurs
        ModeleUtilisateurs --> ControleurUtilisateurs
        deactivate ModeleUtilisateurs
    else pseudo == pseudoLocal
        ControleurUtilisateurs -> AccesUDP : pseudoInvalide(adr)
        activate AccesUDP
        AccesUDP -> TacheEnvoiUDP : TacheEnvoiUDP(msg, adr, broadcast)
        activate TacheEnvoiUDP
        deactivate TacheEnvoiUDP
        AccesUDP --> ControleurUtilisateurs
        deactivate AccesUDP
    end
    deactivate ControleurUtilisateurs
end
@enduml
